name: release

on: workflow_dispatch

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/snapshot-') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Generate Maven Settings
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          repositories: >
            [
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/${env.GITHUB_ACTOR}/*"
              },
              {
                "id": "ossrh",
                "url": "https://s01.oss.sonatype.org/content/groups/public",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          servers: >
            [
              {
                "id": "github",
                "username": "${env.GITHUB_ACTOR}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              },
              {
                "id": "ossrh",
                "username": "${{ secrets.OSS_USERNAME }}",
                "password": "${{ secrets.OSS_PASSWORD }}"
              }
            ]

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Configure Git user
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email ${{ github.actor }}@gmail.com
          git config --local user.signingkey ${{ secrets.GPG_KEY }}
          git config --local commit.gpgsign true

      - name: Prepare Release
        run: mvn -B -U release:prepare -P release,distribution-github

      - run: cp ${{ github.workspace }}/release.properties ${{ github.workspace }}/release.properties.bak

      - name: Perform Release to Github
        run: mvn -B -U release:perform -P release,distribution-github

      - run: mv ${{ github.workspace }}/release.properties.bak ${{ github.workspace }}/release.properties

      - name: Perform Release to Ossrh
        run: mvn -B -U release:perform -P release,distribution-ossrh